# Generated by Django 4.2.11 on 2024-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='column',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
